name: Contact API deployment (production)
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/contact-form-backend-prod.yml
      - cloud-function/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authentication
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_PROD }}

      - name: Deploy function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: send-mail
          runtime: nodejs18
          entry_point: sendMail
          memory_mb: 128
          source_dir: cloud-function
          min_instances: 0
          max_instances: 1
          region: europe-west1
          secret_environment_variables: SENDER_MAIL_ADDRESS=projects/${{ secrets.PROJECT_ID_PROD }}/secrets/SENDER_MAIL_ADDRESS,SENDER_MAIL_PASSWORD=projects/${{ secrets.PROJECT_ID_PROD }}/secrets/SENDER_MAIL_PASSWORD,RECIPIENT_MAIL_ADDRESS=projects/${{ secrets.PROJECT_ID_PROD }}/secrets/RECIPIENT_MAIL_ADDRESS,MAIL_SERVICE=projects/${{ secrets.PROJECT_ID_PROD }}/secrets/MAIL_SERVICE
          env_vars: SITE_KEY=6LcFYgomAAAAAMH7ZZMFkVdjYOgIHs9PnqA4Hz9S