name: Website deployment
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/website-prod.yml
      - website/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authentication
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_PROD }}
          token_format: access_token
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          
      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Push to Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: website/
          file: Dockerfile.prod
          push: true
          tags: |
            europe-west1-docker.pkg.dev/cecile-david-site/website/website:${{ steps.get-tag.outputs.short_ref }}
            europe-west1-docker.pkg.dev/cecile-david-site/website/website:latest

      - name: Deploy new revision
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: website
          image: europe-west1-docker.pkg.dev/cecile-david-site/website/website
          region: europe-west1
